### ISSUE TITLE
[xorg-xinit] Wrong argument passed to mktemp

### ISSUE THREAD

**Issue by alaviss** [PacBSD/abs#22]
In [06_move_serverauthfile_into_tmp.diff](https://github.com/PacBSD/abs/blob/master/extra/xorg-xinit/06_move_serverauthfile_into_tmp.diff#L17), `mktemp` has been passed with an invalid argument `-p` causing `startx` and `xinit` to split out bunch of errors

**Comment by vendion** [comment]
That patch came directly from [Arch Linux's repo](https://git.archlinux.org/svntogit/packages.git/tree/trunk/06_move_serverauthfile_into_tmp.diff?h=packages/xorg-xinit).  Is this not an issue upstream (Arch Linux)?  If so please report there and we will pull the corrected patch.

**Comment by Blub** [comment]
It's not, GNU mktemp does have a `-p` option.

**Comment by alaviss** [comment]
From linux [mktemp(1)](http://linux.die.net/man/1/mktemp)

> **-p DIR**
    use DIR as a prefix; implies -t [deprecated]

**Comment by vendion** [comment]
Okay, I corrected the patch using the absolute path to `/tmp/serverauth.XXXXXXXXXX` instead of the prefix flag, that was very superfluous IMO.
