### ISSUE TITLE
[bash] Requires fdescfs(5) to be mounted at /dev/fd

### ISSUE THREAD

**Issue by alaviss** [PacBSD/abs#23]
`core/bash` were compiled on a machine with [fdescfs(5)][0] mounted so it assume that the resulting environment must have [fdescfs(5)][0] mounted at `/dev/fd` which is incorrect. This cause [makepkg(8)][1] to output dozen of `/dev/fd/62: no such file or directory` lines

---
**FIX**: Either make mounting [fdescfs(8)][0] on `/dev/fd` mandatory or append `bash_cv_dev_fd=absent` to bash `configure`

[0]: https://www.freebsd.org/cgi/man.cgi?query=fdescfs&manpath=FreeBSD+11-current
[1]: https://www.archlinux.org/pacman/makepkg.8.html

**Comment by vendion** [comment]
When building the official packages we use a build jail that does mount `fdescfs` to _/dev/fd_

```
## bash needs fsdescfs for correct operation. This is enabled by default
fdesc	                /dev/fd		        fdescfs		rw	0	0 
```

That should also be present in the default _/etc/fstab_ when installing, if that is missing from your system try adding it and rebuilding `bash` again.

That said I wouldn't be against adding `bash_cv_dev_fd=absent` to the PKGBUILD if there would be no adverse affects in doing so, disclaimer I don't use bash for my SHELL so not familiar with what that would do.

**Comment by alaviss** [comment]
There is an issue with my configuration. [fdescfs(5)](https://www.freebsd.org/cgi/man.cgi?query=fdescfs&manpath=FreeBSD+11-current) is mounted before `/boot` become available, which caused the problem.

**Comment by vendion** [comment]
Glad to hear that you got it resolved.
