### ISSUE TITLE
Library Issues

### ISSUE THREAD

**Issue by markzz** [PacBSD/abs#24]
From the limited testing I've done, I've found that if you install packages such as vim, its dependent libraries are installed in places where the applications cannot link to.

**Comment by vendion** [comment]
Do you have the testing repo enabled in your `/etc/pacman.conf` file?

If so can you report which library it is needing, our [broken packages report](http://users.pacbsd.org/~repo/repo-report/current/verbose.txt) doesn't show that.

If not then you can enable it, sync your repos and update the affected packages, or wait until I have a chance to push them into the stable repos.  That will happen after I get a chance to fix the `libproxy` and `nss` packages.

**Comment by markzz** [comment]
That helped.
