### ISSUE TITLE
talloc: %%PKGCONFIGDIR%% not replaced

### ISSUE THREAD

**Issue by markzz** [PacBSD/abs#25]
When building extra/talloc, instead of the pkgconfig directory being properly set during build, it is kept as `%%PKGCONFIGDIR%%` and creates the directory `/%%PKGCONFIGDIR%%`. This then causes any packages with this as a makedepends to fail (such as tevent).

**Comment by vendion** [comment]
Try removing the _talloc/files/patch-wscript_ patch in the `talloc` directory, and retry building then.  It looks like we may not need that patch as `LIBDIR` variable should be correct for our build system where as things like `%%SOMEVAR%%` is correct for FreeBSDs build system.  The validity of the `fix_test_path.patch` also comes into play as its also dated (Assuming you are trying to update talloc to a newer version and not just building the current version).

The other patches may need updated anyways looking at the Ports tree, those were last updated 4 months ago and our patches are considerably older. https://svnweb.freebsd.org/ports/head/devel/talloc/files/

**Comment by markzz** [comment]
I am updating them, would you like me to file a pull request of whatever I do that builds and seems to function?

**Comment by markzz** [comment]
Removing that patch fixed the problem. Solved.

**Comment by vendion** [comment]
Pull requests would be great.

When you are doing your builds have you setup a build jail on your system so you can do clean builds?  If not instructions for doing so can be found here https://wiki.pacbsd.org/index.php/DeveloperWiki:pac-build
